//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarStoreApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarStoreApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_269619566_KhdApj2KIdQy0rYeXn0HFr13FCbwUM5e {
            get {
                object obj = ResourceManager.GetObject("360_F_269619566_KhdApj2KIdQy0rYeXn0HFr13FCbwUM5e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_294688686_eBbqaZUVeRr8BoCDuhxsWl4fjwV51FcV {
            get {
                object obj = ResourceManager.GetObject("360_F_294688686_eBbqaZUVeRr8BoCDuhxsWl4fjwV51FcV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_887667804_ekudfiOKhD8pkssfLXhhQchVp9xTD9l2 {
            get {
                object obj = ResourceManager.GetObject("360_F_887667804_ekudfiOKhD8pkssfLXhhQchVp9xTD9l2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_91053550_vCOghjH98HboIDGrP2TU8ve1t7rNAEww {
            get {
                object obj = ResourceManager.GetObject("360_F_91053550_vCOghjH98HboIDGrP2TU8ve1t7rNAEww", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_91053550_vCOghjH98HboIDGrP2TU8ve1t7rNAEww1 {
            get {
                object obj = ResourceManager.GetObject("360_F_91053550_vCOghjH98HboIDGrP2TU8ve1t7rNAEww1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5ae05c0b06935fdfbe40e79cd5d86db5 {
            get {
                object obj = ResourceManager.GetObject("5ae05c0b06935fdfbe40e79cd5d86db5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap auto_parts_online {
            get {
                object obj = ResourceManager.GetObject("auto-parts-online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap auto_parts_online1 {
            get {
                object obj = ResourceManager.GetObject("auto-parts-online1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1212230930_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1212230930-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1273682054_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1273682054-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_907671128_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-907671128-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_907671128_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-907671128-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image {
            get {
                object obj = ResourceManager.GetObject("login_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image1 {
            get {
                object obj = ResourceManager.GetObject("login_image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image2 {
            get {
                object obj = ResourceManager.GetObject("login_image2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image3 {
            get {
                object obj = ResourceManager.GetObject("login_image3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image4 {
            get {
                object obj = ResourceManager.GetObject("login_image4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_image5 {
            get {
                object obj = ResourceManager.GetObject("login_image5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_774147 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_774147", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741471 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741471", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_77414710 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_77414710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741472 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741472", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741473 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741473", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741474 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741474", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741475 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741475", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741476 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741476", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741477 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741477", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741478 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741478", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_grunge_wall_texture_scratched_off_white_background_image_7741479 {
            get {
                object obj = ResourceManager.GetObject("pngtree-grunge-wall-texture-scratched-off-white-background-image_7741479", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle_spare_parts_1_1 {
            get {
                object obj = ResourceManager.GetObject("vehicle-spare-parts-1-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle_spare_parts_1_11 {
            get {
                object obj = ResourceManager.GetObject("vehicle-spare-parts-1-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle_spare_parts_1_12 {
            get {
                object obj = ResourceManager.GetObject("vehicle-spare-parts-1-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
